version: "3.9"

services:
  ams:
    build:
      context: ./api-management-system
    ports:
    - "8000:8000"
    volumes:
    - ./api-management-system/ams:/ams
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
    - DB_HOST=db
    - DB_NAME=app
    - DB_USER=postgres
    - DB_PASS=password
    - QS_HOST=qs
#    depends_on:
#    - db

  # Database: Ports to be removed later
  db:
    image: postgres:14-alpine
    environment:
    - POSTGRES_DB=app
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=password
    ports:
    - "5432:5432"